version: "3.9"
services:
  matsim:
    build: .
    command:
    - config.xml
    - --config:controler.lastIteration
    - "10"
    environment:
      MATSIM_OUTPUT_OVERWRITE: "true"
    volumes:
    - type: bind
      source: ${PWD}/test/input
      target: /opt/matsim/data/input
    - type: bind
      source: ${PWD}/test/output
      target: /opt/matsim/data/output